name: app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.0.1
  flutter_easyloading: ^3.0.5
  dio_smart_retry: ^5.0.0
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.6.1
  cached_network_image: ^3.2.3
  card_swiper: ^2.0.4
  easy_refresh: ^3.3.1
  flustars: ^2.0.1
  webview_flutter: ^4.0.7
  stop_watch_timer: ^2.0.0
  pull_to_refresh: ^2.0.0
  avoid_keyboard: ^0.3.0
  flutter_slidable: ^3.0.0
  path_provider: ^2.0.15
  image_gallery_saver: "^1.7.1"
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: "^0.13.1"
  url_launcher: ^6.1.11
  decimal: ^2.3.3
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  crypto: ^3.0.3
  expandable_text: 2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^4.0.0
  group_button: ^5.3.2
  flutter_datetime_picker: ^1.5.1
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/common/app_icon.png"

# flutter_native_splash:
#   background_image: "assets/images/common/launch_image.png"
#   # color: "#FFFFFF"
#   ardroid: true
#   ios: true
#   fullscreen: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/mine/
    - assets/images/discovery/
    - assets/images/chat/
